import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import './SubwayLive.css'
import './GeographicMap.css'

const COLORS={1:'#EE352E',2:'#EE352E',3:'#EE352E',4:'#00933C',5:'#00933C',6:'#00933C',7:'#B933AD',A:'#2850AD',C:'#2850AD',E:'#2850AD',B:'#FF6319',D:'#FF6319',F:'#FF6319',M:'#FF6319',G:'#6CBE45',J:'#996633',Z:'#996633',L:'#A7A9AC',N:'#FCCC0A',Q:'#FCCC0A',R:'#FCCC0A',W:'#FCCC0A'}
const DARK_TEXT=new Set(['N','Q','R','W']),ROUTES=Object.keys(COLORS)
const hash=value=>[...String(value)].reduce((sum,char)=>sum+char.charCodeAt(0),0)
const distinctRouteColors=routes=>routes.reduce((groups,route)=>groups.some(item=>item.color===COLORS[route])?groups:[...groups,{route,color:COLORS[route]||'#82979c'}],[])
const trackKey=point=>`${Number(point[0]).toFixed(5)},${Number(point[1]).toFixed(5)}`
const offsetPath=(map,points,offsets)=>points.map((point,index)=>{const offset=Array.isArray(offsets)?offsets[index]:offsets;if(!offset)return point;const previous=map.latLngToLayerPoint(points[Math.max(0,index-1)]),next=map.latLngToLayerPoint(points[Math.min(points.length-1,index+1)]),current=map.latLngToLayerPoint(point),dx=next.x-previous.x,dy=next.y-previous.y,length=Math.hypot(dx,dy)||1;return map.layerPointToLatLng([current.x-dy/length*offset,current.y+dx/length*offset])})
const nearestPointIndex=(points,lat,lon)=>{let best=0,distance=Infinity;for(let index=0;index<points.length;index++){const point=points[index],next=(point[0]-lat)**2+(point[1]-lon)**2;if(next<distance){distance=next;best=index}}return{index:best,distance}}
const trackPathFor=(train,network)=>{if(!network||!Number.isFinite(train.fromLat)||!Number.isFinite(train.fromLon))return null;let best=null,score=Infinity;for(const shape of network.shapes){if(!shape.routes.includes(train.route))continue;const from=nearestPointIndex(shape.points,train.fromLat,train.fromLon),to=nearestPointIndex(shape.points,train.lat,train.lon),nextScore=from.distance+to.distance;if(nextScore<score){score=nextScore;best={points:shape.points,from:from.index,to:to.index}}}if(!best||score>.00015)return null;const section=best.from<=best.to?best.points.slice(best.from,best.to+1):best.points.slice(best.to,best.from+1).reverse();const points=[[train.fromLat,train.fromLon],...section,[train.lat,train.lon]],distances=[0];for(let index=1;index<points.length;index++){const previous=points[index-1],point=points[index],latScale=Math.cos(point[0]*Math.PI/180),distance=Math.hypot((point[0]-previous[0])*69,(point[1]-previous[1])*69*latScale);distances.push(distances[index-1]+distance)}return{points,distances,total:distances.at(-1)}}
const positionOnTrack=(train,track,now)=>{if(!track||!train.segmentStart||!train.segmentEnd||train.segmentEnd<=train.segmentStart)return{lat:train.lat,lon:train.lon,bearing:train.bearing};const progress=Math.max(0,Math.min(1,(now-train.segmentStart)/(train.segmentEnd-train.segmentStart))),target=track.total*progress;let index=1;while(index<track.distances.length-1&&track.distances[index]<target)index++;const start=track.points[index-1],end=track.points[index],span=track.distances[index]-track.distances[index-1],local=span?Math.max(0,Math.min(1,(target-track.distances[index-1])/span)):0,lat=start[0]+(end[0]-start[0])*local,lon=start[1]+(end[1]-start[1])*local,bearing=(Math.atan2((end[1]-start[1])*Math.cos(lat*Math.PI/180),end[0]-start[0])*180/Math.PI+360)%360;return{lat,lon,bearing}}

const GeographicMap=memo(function GeographicMap({trains,selected,onSelect}){
  const container=useRef(null),mapRef=useRef(null),trainLayer=useRef(null),routeLayer=useRef(null),stopLayer=useRef(null),markerData=useRef(new Map()),[network,setNetwork]=useState(null)
  useEffect(()=>{const controller=new AbortController();fetch('/subway-network.json',{signal:controller.signal}).then(response=>{if(!response.ok)throw Error(`Network map request failed: ${response.status}`);return response.json()}).then(setNetwork).catch(error=>{if(error.name!=='AbortError')console.error(error)});return()=>controller.abort()},[])
  useEffect(()=>{if(mapRef.current)return;const map=L.map(container.current,{center:[40.7128,-73.965],zoom:11,minZoom:10,maxZoom:16,zoomControl:true,attributionControl:true,dragging:true,inertia:true,doubleClickZoom:true,scrollWheelZoom:true,wheelDebounceTime:30,wheelPxPerZoomLevel:80,touchZoom:true,boxZoom:true,keyboard:true,zoomSnap:.5,zoomDelta:.5});L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'© OpenStreetMap © CARTO'}).addTo(map);routeLayer.current=L.layerGroup().addTo(map);stopLayer.current=L.layerGroup().addTo(map);trainLayer.current=L.layerGroup().addTo(map);mapRef.current=map;return()=>{map.remove();mapRef.current=null}},[])
  useEffect(()=>{if(!network||!routeLayer.current||!mapRef.current)return;const map=mapRef.current,routePresence=new Map();network.shapes.forEach(shape=>shape.points.forEach(point=>{const key=trackKey(point),routes=routePresence.get(key)||new Set();shape.routes.forEach(route=>routes.add(route));routePresence.set(key,routes)}));const drawRoutes=()=>{routeLayer.current.clearLayers();network.shapes.forEach(shape=>{const active=!selected||shape.routes.includes(selected),groups=selected&&active?[{route:selected,color:COLORS[selected]}]:distinctRouteColors(shape.routes);if(!active){L.polyline(shape.points,{color:'#82979c',weight:1,opacity:.08,interactive:false}).addTo(routeLayer.current);return}groups.forEach(group=>{const offsets=shape.points.map(point=>{if(selected)return 0;const sharedGroups=distinctRouteColors([...(routePresence.get(trackKey(point))||[])].sort((a,b)=>ROUTES.indexOf(a)-ROUTES.indexOf(b))),index=sharedGroups.findIndex(item=>item.color===group.color);if(index<0||sharedGroups.length<2)return 0;const spacing=sharedGroups.length===2?2.1:3.2;return(index-(sharedGroups.length-1)/2)*spacing}),path=offsetPath(map,shape.points,offsets);L.polyline(path,{color:'#071b24',weight:selected?6:4.6,opacity:selected?.98:.72,interactive:false,lineCap:'round',lineJoin:'round'}).addTo(routeLayer.current);L.polyline(path,{color:group.color,weight:selected?3.8:2.7,opacity:selected?.98:.82,interactive:false,lineCap:'round',lineJoin:'round'}).addTo(routeLayer.current)})})};drawRoutes();map.on('zoomend',drawRoutes);stopLayer.current.clearLayers();network.stations.forEach(station=>{const active=!selected||station.routes.includes(selected);if(!active&&selected)return;const radius=selected?4:2.7,marker=L.circleMarker([station.lat,station.lon],{radius,color:'#f0f7f8',weight:selected?1.6:1.1,fillColor:'#071b24',fillOpacity:1,opacity:selected?.98:.82,interactive:true,bubblingMouseEvents:false});const label=document.createElement('div'),name=document.createElement('strong'),routes=document.createElement('span');name.textContent=station.name;routes.textContent=station.routes.length?station.routes.join(' · '):'Subway station';label.append(name,routes);marker.bindTooltip(label,{className:'station-tooltip',direction:'top',offset:[0,-6],opacity:1});marker.on('mouseover',()=>marker.setStyle({radius:radius+2,fillColor:'#f0f7f8'}));marker.on('mouseout',()=>marker.setStyle({radius,fillColor:'#071b24'}));marker.addTo(stopLayer.current)});return()=>map.off('zoomend',drawRoutes)},[network,selected])
  useEffect(()=>{const layer=trainLayer.current;if(!layer||!network)return;layer.clearLayers();markerData.current.clear();trains.filter(train=>Number.isFinite(train.lat)&&Number.isFinite(train.lon)).slice(0,350).forEach(train=>{const seed=hash(train.id),angle=(seed%360)*Math.PI/180,radius=(seed%5)*.00008,track=trackPathFor(train,network),position=positionOnTrack(train,track,Date.now()/1000),lat=position.lat+Math.sin(angle)*radius,lon=position.lon+Math.cos(angle)*radius,color=COLORS[train.route]||'#fff',dark=DARK_TEXT.has(train.route),bearing=Number.isFinite(position.bearing)?position.bearing:null;const arrowStyle=bearing==null?'visibility:hidden':`transform:rotate(${bearing}deg)`,icon=L.divIcon({className:'live-train-icon',html:`<span style="--train-color:${color};--train-text:${dark?'#111':'#fff'}"><b style="${arrowStyle}">↑</b><em>${train.route}</em></span>`,iconSize:[25,25],iconAnchor:[12.5,12.5]});const marker=L.marker([lat,lon],{icon,keyboard:true,zIndexOffset:1000,title:`${train.route} train toward ${train.nextStop||'next station'}`}).on('click',()=>onSelect(train)).addTo(layer);markerData.current.set(train.id,{marker,train,angle,radius,track})})},[network,trains,onSelect])
  useEffect(()=>{const timer=setInterval(()=>{if(document.hidden)return;const now=Date.now()/1000;markerData.current.forEach(({marker,train,angle,radius,track})=>{const position=positionOnTrack(train,track,now);marker.setLatLng([position.lat+Math.sin(angle)*radius,position.lon+Math.cos(angle)*radius]);const arrow=marker.getElement()?.querySelector('b');if(arrow&&Number.isFinite(position.bearing))arrow.style.transform=`rotate(${position.bearing}deg)`})},1000);return()=>clearInterval(timer)},[])
  return <div ref={container} className="subway-geographic-map" role="application" aria-label="Fixed-scale map of active New York City subway trains"/>
})

function LiveClock(){
  const [clock,setClock]=useState(()=>new Date())
  useEffect(()=>{const update=()=>{if(!document.hidden)setClock(new Date())},timer=setInterval(update,1000);document.addEventListener('visibilitychange',update);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',update)}},[])
  return <p>{clock.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit'})}<small>NEW YORK</small></p>
}

function ExpectedArrival({arrival}){
  const [now,setNow]=useState(()=>Date.now())
  useEffect(()=>{const update=()=>{if(!document.hidden)setNow(Date.now())},timer=setInterval(update,30000);document.addEventListener('visibilitychange',update);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',update)}},[])
  const eta=arrival?Math.max(0,Math.round((arrival-now/1000)/60)):null
  return eta==null?'Tracking':eta<=0?'Due':`${eta} min`
}

export default function SubwayLive(){
  const [data,setData]=useState({trains:[],timestamp:null}),[state,setState]=useState('loading'),[line,setLine]=useState(null),[picked,setPicked]=useState(null),[retry,setRetry]=useState(0)
  useEffect(()=>{let active=true,controller;const load=()=>{if(document.hidden)return;controller?.abort();controller=new AbortController();setState(current=>current==='error'?'loading':current);fetch('/api/subway',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(next=>{if(active){setData(next);setState('live')}}).catch(error=>{if(active&&error.name!=='AbortError'){setData({trains:[],timestamp:null});setState('error')}})};const resume=()=>{if(!document.hidden)load()};load();const refresh=setInterval(load,30000);document.addEventListener('visibilitychange',resume);return()=>{active=false;controller?.abort();clearInterval(refresh);document.removeEventListener('visibilitychange',resume)}},[retry])
  const visible=useMemo(()=>line?data.trains.filter(train=>train.route===line):data.trains,[data.trains,line])
  const counts=useMemo(()=>Object.fromEntries(ROUTES.map(route=>[route,data.trains.filter(train=>train.route===route).length])),[data.trains])
  const selectTrain=useCallback(train=>setPicked(train),[])
  return <main className="subway-live-page">
    <header className="subway-nav">
      <Link to="/projects" className="subway-wordmark">SUBWAY<br/><span>LIVE</span></Link>
      <div className={`live-indicator ${state}`}><i/><span>{state==='loading'?'CONNECTING':state==='live'?'MTA FEED LIVE':'FEED UNAVAILABLE'}</span></div>
      <LiveClock/>
      <Link to="/projects" className="subway-close" aria-label="Back to all projects">×</Link>
    </header>
    <section className="subway-body">
      <aside className="subway-sidebar">
        <p className="subway-eyebrow">Network pulse</p><h1>{data.trains.length}<span>active trips</span></h1>
        <p className="subway-intro">A real-time view of the city in motion. Select a line or tap a train to inspect it.</p>
        <div className="line-picker" aria-label="Filter by subway line"><button className={!line?'selected':''} onClick={()=>{setLine(null);setPicked(null)}}>ALL <b>{data.trains.length}</b></button>{ROUTES.map(route=><button key={route} className={line===route?'selected':''} onClick={()=>{setLine(route);setPicked(null)}} style={{'--route':COLORS[route],'--route-text':DARK_TEXT.has(route)?'#111':'#fff'}}><span>{route}</span><b>{counts[route]}</b></button>)}</div>
        <footer>Data: MTA GTFS-Realtime<br/>Scroll to zoom · drag to move</footer>
      </aside>
      <div className="subway-map">
        {state==='error'?<div className="subway-error" role="alert"><p>LIVE DATA UNAVAILABLE</p><h2>The network is temporarily out of view.</h2><span>We couldn’t reach the MTA feed. No estimated or simulated trains are being shown.</span><button onClick={()=>setRetry(value=>value+1)}>Try again</button></div>:<><GeographicMap trains={visible} selected={line} onSelect={selectTrain}/><div className="map-key"><i/> TRAIN + DIRECTION <span/> SUBWAY STOP</div></>}
      </div>
      <aside className={`train-panel ${picked?'open':''}`}>{picked?<><button onClick={()=>setPicked(null)} aria-label="Close train details">×</button><p className="subway-eyebrow">Selected train</p><div className="route-medallion" style={{background:COLORS[picked.route],color:DARK_TEXT.has(picked.route)?'#111':'#fff'}}>{picked.route}</div><h2>{picked.direction===0?'Northbound':'Southbound'}</h2><dl><div><dt>Next station</dt><dd>{picked.nextStop||'In service'}</dd></div><div><dt>Expected</dt><dd><ExpectedArrival arrival={picked.arrival}/></dd></div><div><dt>Trip ID</dt><dd>{picked.id.slice(-12)}</dd></div></dl></>:<><p className="subway-eyebrow">About this map</p><h2>The city, breathing.</h2><p>Official MTA route geometry and all subway stops are drawn over the city. Each train’s arrow points along its next track segment.</p><div className="panel-stat"><strong>{visible.length}</strong><span>trains in view</span></div></>}</aside>
    </section>
  </main>
}
